-- ============================================================================
-- 1. 用户表
-- ============================================================================
CREATE TABLE IF NOT EXISTS t_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(64) NOT NULL,
    password_hash TEXT NOT NULL,
    email VARCHAR(255) NOT NULL,
    membership_plan_id BIGINT NOT NULL DEFAULT 1,
    status SMALLINT NOT NULL DEFAULT 1,
    deactivated_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE t_users IS '用户表，保存注册用户和认证凭据';
COMMENT ON COLUMN t_users.id IS '用户 ID，自增主键';
COMMENT ON COLUMN t_users.username IS '登录用户名';
COMMENT ON COLUMN t_users.password_hash IS '密码哈希值，不保存明文密码';
COMMENT ON COLUMN t_users.email IS '用户邮箱，用于邮箱验证码登录和账号找回';
COMMENT ON COLUMN t_users.membership_plan_id IS '用户当前绑定的会员计划 ID，由应用层保证计划存在';
COMMENT ON COLUMN t_users.status IS '用户状态：1=正常，2=禁用，3=注销冷静期';
COMMENT ON COLUMN t_users.deactivated_at IS '用户进入注销冷静期的时间，超过 7 天后可由清理任务删除资产';
COMMENT ON COLUMN t_users.created_at IS '创建时间';
COMMENT ON COLUMN t_users.updated_at IS '更新时间';

ALTER TABLE t_users ADD CONSTRAINT t_users_email_key UNIQUE (email);

-- ============================================================================
-- 2. 用户设置表
-- ============================================================================
CREATE TABLE IF NOT EXISTS t_user_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE,
    settings JSONB NOT NULL DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE t_user_settings IS '用户设置表，保存用户级偏好、模型配置和通知选项';
COMMENT ON COLUMN t_user_settings.id IS '设置 ID，自增主键';
COMMENT ON COLUMN t_user_settings.user_id IS '所属用户 ID';
COMMENT ON COLUMN t_user_settings.settings IS '用户设置 JSON，保存模型、主题、通知、下载等偏好';
COMMENT ON COLUMN t_user_settings.created_at IS '创建时间';
COMMENT ON COLUMN t_user_settings.updated_at IS '更新时间';

-- ============================================================================
-- 3. 模型配置表
-- ============================================================================
CREATE TABLE IF NOT EXISTS t_models (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL DEFAULT 0,
    name VARCHAR(100) NOT NULL,
    provider VARCHAR(40) NOT NULL DEFAULT 'custom_openai',
    model_id VARCHAR(120) NOT NULL DEFAULT '',
    api_url TEXT NOT NULL DEFAULT '',
    api_key TEXT NOT NULL DEFAULT '',
    top_p NUMERIC(4, 3) NOT NULL DEFAULT 0.9 CHECK (top_p >= 0 AND top_p <= 1),
    temperature NUMERIC(4, 2) NOT NULL DEFAULT 0.7 CHECK (temperature >= 0 AND temperature <= 2),
    status SMALLINT NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    UNIQUE (user_id, name)
);

COMMENT ON TABLE t_models IS '模型配置表，保存内置模型和用户自定义模型';
COMMENT ON COLUMN t_models.id IS '模型 ID，自增主键';
COMMENT ON COLUMN t_models.user_id IS '所属用户 ID，0 表示内置模型';
COMMENT ON COLUMN t_models.name IS '模型显示名称';
COMMENT ON COLUMN t_models.provider IS '模型厂商';
COMMENT ON COLUMN t_models.model_id IS '厂商侧模型 ID';
COMMENT ON COLUMN t_models.api_url IS '模型 API 地址';
COMMENT ON COLUMN t_models.api_key IS '模型 API Key';
COMMENT ON COLUMN t_models.top_p IS 'Top-p 参数';
COMMENT ON COLUMN t_models.temperature IS '温度参数';
COMMENT ON COLUMN t_models.status IS '模型状态：1=启用，2=禁用';
COMMENT ON COLUMN t_models.created_at IS '创建时间';
COMMENT ON COLUMN t_models.updated_at IS '更新时间';

-- ============================================================================
-- 4. 小说表
-- ============================================================================
CREATE TABLE IF NOT EXISTS t_novels (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    title TEXT NOT NULL DEFAULT '未命名小说',
    plan_data JSONB NOT NULL DEFAULT '{"title":"未命名小说","summary":""}'::jsonb,
    setup_original_text TEXT NOT NULL DEFAULT '',
    status SMALLINT NOT NULL DEFAULT 1,
    word_count INTEGER NOT NULL DEFAULT 0 CHECK (word_count >= 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    archived_at TIMESTAMPTZ
);

COMMENT ON TABLE t_novels IS '小说表，保存用户创建的小说及生命周期状态';
COMMENT ON COLUMN t_novels.id IS '小说 ID，自增主键';
COMMENT ON COLUMN t_novels.user_id IS '所属用户 ID';
COMMENT ON COLUMN t_novels.title IS '小说名称，由用户新建小说时填写，独立于 plan_data 便于列表排序和导出';
COMMENT ON COLUMN t_novels.plan_data IS '小说结构化规划 JSON，保存新建小说表单初始化数据和后续 AI 全书规划字段';
COMMENT ON COLUMN t_novels.setup_original_text IS '新建小说自动生成模板时的用户原始描述，仅用于前端回填，不进入 AI 规划上下文';
COMMENT ON COLUMN t_novels.status IS '小说状态：1=设定暂存，2=正式创作，3=已归档';
COMMENT ON COLUMN t_novels.word_count IS '小说总字数';
COMMENT ON COLUMN t_novels.created_at IS '创建时间';
COMMENT ON COLUMN t_novels.updated_at IS '更新时间';
COMMENT ON COLUMN t_novels.archived_at IS '归档时间，未归档为空';

-- ============================================================================
-- 5. 卷表
-- ============================================================================
CREATE TABLE IF NOT EXISTS t_volumes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    novel_id BIGINT NOT NULL,
    plan_data JSONB NOT NULL DEFAULT '{"title":"未命名卷","summary":""}'::jsonb,
    sort_order INTEGER NOT NULL,
    status SMALLINT NOT NULL DEFAULT 1,
    word_count INTEGER NOT NULL DEFAULT 0 CHECK (word_count >= 0),
    is_deleted SMALLINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE t_volumes IS '卷表，保存小说下的有序卷结构';
COMMENT ON COLUMN t_volumes.id IS '卷 ID，自增主键';
COMMENT ON COLUMN t_volumes.novel_id IS '所属小说 ID';
COMMENT ON COLUMN t_volumes.plan_data IS '卷结构化规划 JSON，保存 AI 返回的完整卷规划项';
COMMENT ON COLUMN t_volumes.sort_order IS '卷在小说中的排序序号';
COMMENT ON COLUMN t_volumes.status IS '卷状态：1=草稿，2=已完成';
COMMENT ON COLUMN t_volumes.word_count IS '卷总字数';
COMMENT ON COLUMN t_volumes.is_deleted IS '软删除标记：0=未删除，1=已删除';
COMMENT ON COLUMN t_volumes.created_at IS '创建时间';
COMMENT ON COLUMN t_volumes.updated_at IS '更新时间';

-- ============================================================================
-- 6. 章节表
-- ============================================================================
CREATE TABLE IF NOT EXISTS t_chapters (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    volume_id BIGINT NOT NULL,
    plan_data JSONB NOT NULL DEFAULT '{}'::jsonb,
    sort_order INTEGER NOT NULL,
    status SMALLINT NOT NULL DEFAULT 1,
    word_count INTEGER NOT NULL DEFAULT 0 CHECK (word_count >= 0),
    is_deleted SMALLINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    completed_at TIMESTAMPTZ
);

COMMENT ON TABLE t_chapters IS '章节表，保存卷下的有序章节结构';
COMMENT ON COLUMN t_chapters.id IS '章节 ID，自增主键';
COMMENT ON COLUMN t_chapters.volume_id IS '所属卷 ID';
COMMENT ON COLUMN t_chapters.plan_data IS '章节结构化规划 JSON，保存章节梗概、出场人物、关键事件、伏笔、前后呼应、写作重点和结尾钩子';
COMMENT ON COLUMN t_chapters.sort_order IS '章节在卷中的排序序号';
COMMENT ON COLUMN t_chapters.status IS '章节状态：1=草稿，2=已完成';
COMMENT ON COLUMN t_chapters.word_count IS '章节字数';
COMMENT ON COLUMN t_chapters.is_deleted IS '软删除标记：0=未删除，1=已删除';
COMMENT ON COLUMN t_chapters.created_at IS '创建时间';
COMMENT ON COLUMN t_chapters.updated_at IS '更新时间';
COMMENT ON COLUMN t_chapters.completed_at IS '完成时间，未完成为空';

-- ============================================================================
-- 7. 章节正文表
-- ============================================================================
CREATE TABLE IF NOT EXISTS t_chapter_contents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chapter_id BIGINT NOT NULL,
    content TEXT NOT NULL DEFAULT '',
    source_message_id BIGINT NOT NULL DEFAULT 0,
    status SMALLINT NOT NULL DEFAULT 2,
    word_count INTEGER NOT NULL DEFAULT 0 CHECK (word_count >= 0),
    draft_type SMALLINT NOT NULL DEFAULT 1,
    origin_draft_id BIGINT NOT NULL DEFAULT 0,
    draft_name TEXT NOT NULL DEFAULT '',
    is_deleted SMALLINT NOT NULL DEFAULT 0,
    used_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE t_chapter_contents IS '章节正文表，保存每章可编辑正文';
COMMENT ON COLUMN t_chapter_contents.id IS '正文 ID，自增主键';
COMMENT ON COLUMN t_chapter_contents.chapter_id IS '所属章节 ID';
COMMENT ON COLUMN t_chapter_contents.content IS '章节正文内容';
COMMENT ON COLUMN t_chapter_contents.source_message_id IS '正文草稿来源助手消息 ID，0 表示旧数据或非对话生成';
COMMENT ON COLUMN t_chapter_contents.status IS '正文状态：1=草稿，2=当前正文';
COMMENT ON COLUMN t_chapter_contents.word_count IS '正文非空白字数';
COMMENT ON COLUMN t_chapter_contents.draft_type IS '草稿类型：1=AI原始草稿，2=可编辑草稿';
COMMENT ON COLUMN t_chapter_contents.origin_draft_id IS '可编辑草稿来源的 AI 原始草稿 ID，0 表示无来源或旧数据';
COMMENT ON COLUMN t_chapter_contents.draft_name IS '草稿名称，用于编辑器中区分多个可编辑正文草稿';
COMMENT ON COLUMN t_chapter_contents.is_deleted IS '软删除标记：0=未删除，1=已删除';
COMMENT ON COLUMN t_chapter_contents.used_at IS '草稿被设为当前正文的时间，未使用为空';
COMMENT ON COLUMN t_chapter_contents.created_at IS '创建时间';
COMMENT ON COLUMN t_chapter_contents.updated_at IS '更新时间';

-- ============================================================================
-- 8. 对话会话表
-- ============================================================================
CREATE TABLE IF NOT EXISTS t_chat_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    scope_type SMALLINT NOT NULL,
    scope_id BIGINT NOT NULL,
    title VARCHAR(200) NOT NULL DEFAULT '',
    is_deleted SMALLINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE t_chat_sessions IS '对话会话表，保存小说、卷、章节级 AI 对话会话';
COMMENT ON COLUMN t_chat_sessions.id IS '对话会话 ID，自增主键';
COMMENT ON COLUMN t_chat_sessions.user_id IS '所属用户 ID';
COMMENT ON COLUMN t_chat_sessions.scope_type IS '对话范围类型：1=小说，2=卷，3=章节';
COMMENT ON COLUMN t_chat_sessions.scope_id IS '对话范围对象 ID，对应小说、卷或章节 ID';
COMMENT ON COLUMN t_chat_sessions.title IS '会话标题';
COMMENT ON COLUMN t_chat_sessions.is_deleted IS '软删除标记：0=未删除，1=已删除';
COMMENT ON COLUMN t_chat_sessions.created_at IS '创建时间';
COMMENT ON COLUMN t_chat_sessions.updated_at IS '更新时间';

-- ============================================================================
-- 9. 对话消息表
-- ============================================================================
CREATE TABLE IF NOT EXISTS t_chat_messages (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id BIGINT NOT NULL,
    role SMALLINT NOT NULL,
    content TEXT NOT NULL,
    render_data JSONB NOT NULL DEFAULT '{}'::jsonb,
    is_deleted SMALLINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE t_chat_messages IS '对话消息表，保存 AI 对话消息和计划内容';
COMMENT ON COLUMN t_chat_messages.id IS '对话消息 ID，自增主键';
COMMENT ON COLUMN t_chat_messages.session_id IS '所属会话 ID';
COMMENT ON COLUMN t_chat_messages.role IS '消息角色：1=用户，2=AI助手，3=系统';
COMMENT ON COLUMN t_chat_messages.content IS '消息正文';
COMMENT ON COLUMN t_chat_messages.render_data IS '消息结构化渲染数据，保存规划卡片、正文草稿等 UI 数据，避免污染正文内容';
COMMENT ON COLUMN t_chat_messages.is_deleted IS '软删除标记：0=未删除，1=已删除';
COMMENT ON COLUMN t_chat_messages.created_at IS '创建时间';

-- ============================================================================
-- 10. AI 运行记录表
-- ============================================================================
CREATE TABLE IF NOT EXISTS t_model_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    scope_type SMALLINT NOT NULL,
    scope_id BIGINT,
    model_id BIGINT NOT NULL DEFAULT 0,
    status SMALLINT NOT NULL DEFAULT 0,
    token_count BIGINT NOT NULL DEFAULT 0,
    finish_reason TEXT NOT NULL DEFAULT '',
    error_message TEXT NOT NULL DEFAULT '',
    start_time TIMESTAMPTZ NOT NULL DEFAULT now(),
    end_time TIMESTAMPTZ
);

COMMENT ON TABLE t_model_runs IS 'AI 运行记录表，保存每次模型调用的运行元数据，避免污染对话消息表';
COMMENT ON COLUMN t_model_runs.id IS '运行记录 ID，自增主键';
COMMENT ON COLUMN t_model_runs.user_id IS '发起运行的用户 ID，由应用层保证用户存在';
COMMENT ON COLUMN t_model_runs.scope_type IS '运行范围类型：1=对话消息，2=新建小说设定生成，3=草稿润色，4=草稿校验';
COMMENT ON COLUMN t_model_runs.scope_id IS '运行范围对象 ID：消息为 t_chat_messages.id，新建小说设定生成为空，润色和校验为 t_chapter_contents.id';
COMMENT ON COLUMN t_model_runs.model_id IS '使用的模型配置 ID，对应 t_models.id，0 表示未解析到模型';
COMMENT ON COLUMN t_model_runs.status IS '运行状态：0=运行中，1=成功，2=失败，3=取消';
COMMENT ON COLUMN t_model_runs.token_count IS '模型返回的 token 消耗数，未返回时为 0';
COMMENT ON COLUMN t_model_runs.finish_reason IS '模型结束原因，未返回时为空字符串';
COMMENT ON COLUMN t_model_runs.error_message IS '失败时的错误摘要，成功时为空字符串';
COMMENT ON COLUMN t_model_runs.start_time IS '运行开始时间';
COMMENT ON COLUMN t_model_runs.end_time IS '运行结束时间，运行中为空';

-- ============================================================================
-- 11. 会员计划表
-- ============================================================================
CREATE TABLE IF NOT EXISTS t_membership_plans (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(64) NOT NULL UNIQUE,
    level SMALLINT NOT NULL DEFAULT 1,
    features JSONB NOT NULL DEFAULT '{"max_concurrent_streams":3}'::jsonb,
    status SMALLINT NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE t_membership_plans IS '会员计划表，集中保存不同会员计划及其权益配置';
COMMENT ON COLUMN t_membership_plans.id IS '会员计划 ID，自增主键';
COMMENT ON COLUMN t_membership_plans.name IS '会员计划名称，如默认计划、专业版计划';
COMMENT ON COLUMN t_membership_plans.level IS '会员计划等级：1=默认计划，后续可扩展更高等级';
COMMENT ON COLUMN t_membership_plans.features IS '会员计划权益配置，保存最大 AI 并发数等可变福利';
COMMENT ON COLUMN t_membership_plans.status IS '会员计划状态：1=启用，2=禁用';
COMMENT ON COLUMN t_membership_plans.created_at IS '创建时间';
COMMENT ON COLUMN t_membership_plans.updated_at IS '更新时间';

-- ============================================================================
-- 12. 用户反馈表
-- ============================================================================
CREATE TABLE IF NOT EXISTS t_user_feedbacks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    content TEXT NOT NULL,
    image_urls JSONB NOT NULL DEFAULT '[]'::jsonb,
    status SMALLINT NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

COMMENT ON TABLE t_user_feedbacks IS '用户反馈表，保存用户在帮助与反馈中提交的问题和建议，供后续管理后台查看';
COMMENT ON COLUMN t_user_feedbacks.id IS '反馈 ID，自增主键';
COMMENT ON COLUMN t_user_feedbacks.user_id IS '提交反馈的用户 ID，由应用层保证用户存在';
COMMENT ON COLUMN t_user_feedbacks.content IS '用户反馈内容，不能为空';
COMMENT ON COLUMN t_user_feedbacks.image_urls IS '反馈图片链接数组，保存用户上传到对象存储后的公开访问链接';
COMMENT ON COLUMN t_user_feedbacks.status IS '反馈处理状态：1=未处理，2=处理中，3=已处理';
COMMENT ON COLUMN t_user_feedbacks.created_at IS '创建时间';
COMMENT ON COLUMN t_user_feedbacks.updated_at IS '更新时间';

-- ============================================================================
-- 索引
-- ============================================================================
CREATE INDEX IF NOT EXISTS idx_t_novels_user_status ON t_novels(user_id, status);
CREATE INDEX IF NOT EXISTS idx_t_novels_user_title ON t_novels(user_id, title);
CREATE INDEX IF NOT EXISTS idx_t_volumes_novel_order ON t_volumes(novel_id, sort_order) WHERE is_deleted = 0; -- 加速未删除卷列表按小说顺序加载
CREATE UNIQUE INDEX IF NOT EXISTS idx_t_volumes_novel_sort_active ON t_volumes(novel_id, sort_order) WHERE is_deleted = 0; -- 保证同一小说下未删除卷排序唯一
CREATE INDEX IF NOT EXISTS idx_t_chapters_volume_order ON t_chapters(volume_id, sort_order) WHERE is_deleted = 0; -- 加速未删除章节列表按卷顺序加载
CREATE UNIQUE INDEX IF NOT EXISTS idx_t_chapters_volume_sort_active ON t_chapters(volume_id, sort_order) WHERE is_deleted = 0; -- 保证同一卷下未删除章节排序唯一
CREATE INDEX IF NOT EXISTS idx_t_chat_sessions_user_scope ON t_chat_sessions(user_id, scope_type, scope_id) WHERE is_deleted = 0; -- 加速定位未删除对话会话
CREATE INDEX IF NOT EXISTS idx_t_chat_messages_session_created ON t_chat_messages(session_id, created_at) WHERE is_deleted = 0; -- 加速按时间加载未删除会话消息
CREATE INDEX IF NOT EXISTS idx_t_chat_messages_render_data ON t_chat_messages USING GIN (render_data);
CREATE INDEX IF NOT EXISTS idx_t_user_settings_settings ON t_user_settings USING GIN (settings);
CREATE INDEX IF NOT EXISTS idx_t_models_user_status ON t_models(user_id, status);
CREATE INDEX IF NOT EXISTS idx_t_chapter_contents_chapter_status ON t_chapter_contents(chapter_id, status, updated_at DESC) WHERE is_deleted = 0; -- 加速读取未删除章节正文
CREATE UNIQUE INDEX IF NOT EXISTS idx_t_chapter_contents_one_active ON t_chapter_contents(chapter_id) WHERE status = 2 AND is_deleted = 0; -- 保证同一章节最多一篇未删除当前正文
CREATE INDEX IF NOT EXISTS idx_t_chapter_contents_editable_drafts ON t_chapter_contents(chapter_id, draft_type, updated_at DESC) WHERE is_deleted = 0; -- 加速读取未删除可编辑草稿
CREATE INDEX IF NOT EXISTS idx_t_membership_plans_status_level ON t_membership_plans(status, level);
CREATE INDEX IF NOT EXISTS idx_t_membership_plans_features ON t_membership_plans USING GIN (features);
CREATE INDEX IF NOT EXISTS idx_t_users_membership_plan ON t_users(membership_plan_id);
CREATE INDEX IF NOT EXISTS idx_t_users_status ON t_users(status);
CREATE INDEX IF NOT EXISTS idx_t_users_status_deactivated_at ON t_users(status, deactivated_at);
CREATE INDEX IF NOT EXISTS idx_t_user_feedbacks_status_created ON t_user_feedbacks(status, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_t_user_feedbacks_user_created ON t_user_feedbacks(user_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_t_user_feedbacks_image_urls ON t_user_feedbacks USING GIN (image_urls);
CREATE INDEX IF NOT EXISTS idx_t_model_runs_user_start ON t_model_runs(user_id, start_time DESC);
CREATE INDEX IF NOT EXISTS idx_t_model_runs_scope ON t_model_runs(scope_type, scope_id);
CREATE INDEX IF NOT EXISTS idx_t_model_runs_model_start ON t_model_runs(model_id, start_time DESC);
CREATE INDEX IF NOT EXISTS idx_t_model_runs_status_start ON t_model_runs(status, start_time DESC);

COMMENT ON INDEX idx_t_novels_user_status IS '加速按用户和状态查询小说列表';
COMMENT ON INDEX idx_t_novels_user_title IS '按用户和小说名称检索小说时使用';
COMMENT ON INDEX idx_t_volumes_novel_order IS '加速按小说加载有序卷列表';
COMMENT ON INDEX idx_t_volumes_novel_sort_active IS '保证同一小说下未删除卷的排序序号唯一';
COMMENT ON INDEX idx_t_chapters_volume_order IS '加速按卷加载有序章节列表';
COMMENT ON INDEX idx_t_chapters_volume_sort_active IS '保证同一卷下未删除章节的排序序号唯一';
COMMENT ON INDEX idx_t_chat_sessions_user_scope IS '加速按用户和范围定位对话会话';
COMMENT ON INDEX idx_t_chat_messages_session_created IS '加速按时间加载会话消息';
COMMENT ON INDEX idx_t_chat_messages_render_data IS '加速按消息结构化渲染数据排查和扩展查询';
COMMENT ON INDEX idx_t_user_settings_settings IS '加速按用户设置 JSON 内容查询';
COMMENT ON INDEX idx_t_models_user_status IS '加速按用户和模型状态查询可用模型';
COMMENT ON INDEX idx_t_chapter_contents_chapter_status IS '加速按章节读取草稿和当前正文';
COMMENT ON INDEX idx_t_chapter_contents_one_active IS '保证同一章节最多只有一篇当前正文';
COMMENT ON INDEX idx_t_chapter_contents_editable_drafts IS '加速按章节读取未删除的可编辑草稿列表';
COMMENT ON INDEX idx_t_membership_plans_status_level IS '加速查询启用会员计划';
COMMENT ON INDEX idx_t_membership_plans_features IS '加速后续按权益 JSON 内容查询会员计划';
COMMENT ON INDEX idx_t_users_membership_plan IS '加速按会员计划筛选用户';
COMMENT ON INDEX idx_t_users_status IS '加速过滤正常、禁用或注销冷静期用户';
COMMENT ON INDEX idx_t_users_status_deactivated_at IS '加速查询处于注销冷静期且超过 7 天的用户';
COMMENT ON INDEX idx_t_user_feedbacks_status_created IS '加速后续管理后台按处理状态和时间拉取反馈';
COMMENT ON INDEX idx_t_user_feedbacks_user_created IS '加速按用户查看反馈提交历史';
COMMENT ON INDEX idx_t_user_feedbacks_image_urls IS '加速后续管理后台按图片链接 JSON 检索反馈';
COMMENT ON INDEX idx_t_model_runs_user_start IS '加速按用户和开始时间查看 AI 运行记录';
COMMENT ON INDEX idx_t_model_runs_scope IS '加速按业务范围定位 AI 运行记录';
COMMENT ON INDEX idx_t_model_runs_model_start IS '加速按模型和开始时间统计 AI 运行记录';
COMMENT ON INDEX idx_t_model_runs_status_start IS '加速按运行状态和开始时间排查 AI 调用结果';

-- ============================================================================
-- 初始数据
-- ============================================================================

-- 默认内置模型（DeepSeek 官方模型，API Key 请替换为实际值）
INSERT INTO t_models (user_id, name, provider, model_id, api_url, api_key, top_p, temperature, status)
VALUES
    (0, '官方模型', 'deepseek', 'deepseek-v4-flash', 'https://api.deepseek.com', 'sk-9c1434fd6a9249679734cb18df9ab681', 0.9, 0.7, 1)
ON CONFLICT (user_id, name) DO NOTHING;

-- 默认会员计划
INSERT INTO t_membership_plans (id, name, level, features, status)
VALUES (1, '默认计划', 1, '{"max_concurrent_streams":3}'::jsonb, 1)
ON CONFLICT (id) DO NOTHING;
